/**
 * Solar-Battery-Load System Simulator
 * Calculation Utilities
 * 
 * This module contains all the energy calculation functions
 * using simplified first-order models suitable for educational purposes.
 */

// ============================================
// SOLAR CALCULATIONS
// ============================================

/**
 * Calculates the effective daily energy generated by a solar array.
 * 
 * @param {Object} config - Solar configuration
 * @param {number} config.panelWattage - Individual panel wattage (W)
 * @param {number} config.numberOfPanels - Number of panels in array
 * @param {number} config.sunHours - Peak sun hours per day (hours)
 * @param {number} config.tiltEfficiency - Panel tilt/orientation efficiency (0-1)
 * @param {number} config.temperatureLoss - Temperature-related loss factor (0-1)
 * @param {number} config.soilingLoss - Dust/soiling loss factor (0-1)
 * @param {number} config.degradation - Panel aging/degradation factor (0-1)
 * @returns {Object} Solar output calculations
 */
export function calculateSolarOutput(config) {
    const {
        panelWattage,
        numberOfPanels,
        sunHours,
        tiltEfficiency,
        temperatureLoss,
        soilingLoss,
        degradation
    } = config;

    // Total installed capacity (peak watts)
    const installedCapacityW = panelWattage * numberOfPanels;

    // Combined efficiency factor
    const combinedEfficiency = tiltEfficiency * (1 - temperatureLoss) * (1 - soilingLoss) * (1 - degradation);

    // Effective capacity after losses
    const effectiveCapacityW = installedCapacityW * combinedEfficiency;

    // Daily energy generation (Wh/day)
    // Formula: Effective Capacity (W) × Sun Hours (h) = Energy (Wh)
    const dailyEnergyWh = effectiveCapacityW * sunHours;

    return {
        installedCapacityW,
        combinedEfficiency,
        effectiveCapacityW,
        dailyEnergyWh,
        // Hourly average power (for visualization)
        averagePowerW: dailyEnergyWh / 24
    };
}

/**
 * Generates hourly solar generation profile for visualization.
 * Uses a simplified bell curve centered around noon.
 * 
 * @param {number} dailyEnergyWh - Total daily energy generation (Wh)
 * @param {number} sunHours - Peak sun hours per day
 * @returns {number[]} Array of 24 hourly generation values (Wh)
 */
export function generateSolarProfile(dailyEnergyWh, sunHours) {
    const profile = [];
    const peakHour = 12; // Solar peak at noon
    const sigma = sunHours / 2.5; // Spread based on sun hours

    // Explicit daylight bounds
    const sunrise = 8;
    const sunset = 18;

    // Generate Gaussian-like distribution
    let sum = 0;
    for (let hour = 0; hour < 24; hour++) {
        // No solar power outside daylight hours
        if (hour < sunrise || hour >= sunset) {
            profile.push(0);
            continue;
        }

        // Gaussian distribution centered at noon
        const value = Math.exp(-Math.pow(hour - peakHour, 2) / (2 * sigma * sigma));
        profile.push(value);
        sum += value;
    }

    // Normalize to match total daily energy
    return profile.map(v => sum > 0 ? (v / sum) * dailyEnergyWh : 0);
}


// ============================================
// BATTERY CALCULATIONS
// ============================================

/**
 * Battery chemistry efficiency factors (simplified).
 * These represent round-trip efficiency.
 */
export const BATTERY_CHEMISTRY = {
    'lead-acid': { efficiency: 0.80, label: 'Lead-Acid (80%)' },
    'agm': { efficiency: 0.85, label: 'AGM (85%)' },
    'gel': { efficiency: 0.82, label: 'Gel (82%)' },
    'lithium-ion': { efficiency: 0.95, label: 'Lithium-Ion (95%)' },
    'lifepo4': { efficiency: 0.98, label: 'LiFePO4 (98%)' }
};

/**
 * Calculates battery storage capacity and related metrics.
 * 
 * @param {Object} config - Battery configuration
 * @param {number} config.voltage - Battery bank voltage (V)
 * @param {number} config.capacity - Battery capacity (Ah)
 * @param {string} config.chemistry - Battery chemistry type
 * @param {number} config.depthOfDischarge - Maximum DoD allowed (0-1)
 * @param {number} config.chargeEfficiency - Charging efficiency (0-1)
 * @param {number} config.dischargeEfficiency - Discharging efficiency (0-1)
 * @returns {Object} Battery calculations
 */
export function calculateBatteryStorage(config) {
    const {
        voltage,
        capacity,
        chemistry,
        depthOfDischarge,
        chargeEfficiency,
        dischargeEfficiency
    } = config;

    // Total stored energy (Wh)
    const totalEnergyWh = voltage * capacity;

    // Usable energy considering DoD
    const usableEnergyWh = totalEnergyWh * depthOfDischarge;

    // Chemistry efficiency
    const chemistryEfficiency = BATTERY_CHEMISTRY[chemistry]?.efficiency || 0.85;

    // Effective usable energy after round-trip losses
    const effectiveUsableWh = usableEnergyWh * chargeEfficiency * dischargeEfficiency * chemistryEfficiency;

    return {
        totalEnergyWh,
        usableEnergyWh,
        effectiveUsableWh,
        chemistryEfficiency,
        roundTripEfficiency: chargeEfficiency * dischargeEfficiency * chemistryEfficiency
    };
}

/**
 * Calculates battery autonomy (how long battery can power load alone).
 * 
 * @param {number} usableEnergyWh - Usable battery energy (Wh)
 * @param {number} loadPowerW - Total load power draw (W)
 * @returns {number} Autonomy in hours
 */
export function calculateBatteryAutonomy(usableEnergyWh, loadPowerW) {
    if (loadPowerW <= 0) return Infinity;
    return usableEnergyWh / loadPowerW;
}


// ============================================
// LOAD CALCULATIONS
// ============================================

/**
 * Load type characteristics.
 * Power factor affects effective power draw.
 */
export const LOAD_TYPES = {
    'resistive': { powerFactor: 1.0, label: 'Resistive (Heater, Incandescent)', startupMultiplier: 1.0 },
    'inductive': { powerFactor: 0.8, label: 'Inductive (Motor, Compressor)', startupMultiplier: 3.0 },
    'capacitive': { powerFactor: 0.9, label: 'Capacitive (LED Driver, SMPS)', startupMultiplier: 1.5 },
    'mixed': { powerFactor: 0.85, label: 'Mixed Load', startupMultiplier: 2.0 }
};

/**
 * Calculates total daily energy consumption from loads.
 * 
 * @param {Array} loads - Array of load configurations
 * @param {string} loads[].name - Load name
 * @param {string} loads[].type - Load type (resistive, inductive, etc.)
 * @param {number} loads[].powerW - Power rating (W)
 * @param {number} loads[].hoursPerDay - Operating hours per day
 * @param {number} loads[].priority - Priority level (1-5, lower is higher priority)
 * @returns {Object} Load calculations
 */
export function calculateLoadConsumption(loads) {
    let totalDailyWh = 0;
    let peakDemandW = 0;

    const loadDetails = loads.map(load => {
        const loadType = LOAD_TYPES[load.type] || LOAD_TYPES.mixed;

        // Effective power considering power factor (simplified DC equivalent)
        const effectivePowerW = load.powerW / loadType.powerFactor;

        // Daily energy for this load
        const dailyWh = effectivePowerW * load.hoursPerDay;

        totalDailyWh += dailyWh;
        peakDemandW += effectivePowerW;

        return {
            ...load,
            effectivePowerW,
            dailyWh,
            startupPowerW: effectivePowerW * loadType.startupMultiplier
        };
    });

    return {
        totalDailyWh,
        peakDemandW,
        averagePowerW: totalDailyWh / 24,
        loads: loadDetails
    };
}

/**
 * Generates hourly load profile based on load schedules.
 * 
 * @param {Array} loads - Array of load configurations with timing
 * @returns {number[]} Array of 24 hourly consumption values (Wh)
 */
export function generateLoadProfile(loads) {
    const profile = new Array(24).fill(0);

    loads.forEach(load => {
        const loadType = LOAD_TYPES[load.type] || LOAD_TYPES.mixed;
        const effectivePowerW = load.powerW / loadType.powerFactor;
        const startHour = load.startHour || 8;
        const hoursOn = load.hoursPerDay;

        for (let i = 0; i < hoursOn; i++) {
            const hour = (startHour + i) % 24;
            profile[hour] += effectivePowerW;
        }
    });

    return profile;
}


// ============================================
// SYSTEM ANALYSIS
// ============================================

/**
 * Analyzes the complete system energy balance.
 * 
 * @param {Object} solarOutput - Output from calculateSolarOutput
 * @param {Object} batteryStorage - Output from calculateBatteryStorage
 * @param {Object} loadConsumption - Output from calculateLoadConsumption
 * @returns {Object} System analysis results
 */
export function analyzeSystem(solarOutput, batteryStorage, loadConsumption) {
    const { dailyEnergyWh: solarDailyWh } = solarOutput;
    const { effectiveUsableWh: batteryUsableWh } = batteryStorage;
    const { totalDailyWh: loadDailyWh, peakDemandW, averagePowerW: loadAvgW } = loadConsumption;

    // Net energy balance
    const netEnergyBalance = solarDailyWh - loadDailyWh;

    // Battery autonomy (hours without solar)
    const batteryAutonomyHours = calculateBatteryAutonomy(batteryUsableWh, loadAvgW);

    // Days of autonomy
    const autonomyDays = batteryAutonomyHours / 24;

    // System sustainability analysis
    let sustainabilityStatus;
    let sustainabilityScore;

    if (netEnergyBalance >= 0) {
        // System generates enough or excess energy
        const excessPercent = (netEnergyBalance / loadDailyWh) * 100;
        if (excessPercent >= 20) {
            sustainabilityStatus = 'sustainable';
            sustainabilityScore = Math.min(100, 70 + excessPercent);
        } else if (excessPercent >= 0) {
            sustainabilityStatus = 'marginal';
            sustainabilityScore = 50 + excessPercent;
        }
    } else {
        // System has energy deficit
        const deficitPercent = Math.abs(netEnergyBalance / loadDailyWh) * 100;
        if (deficitPercent <= 10) {
            sustainabilityStatus = 'marginal';
            sustainabilityScore = 50 - deficitPercent * 2;
        } else {
            sustainabilityStatus = 'unstable';
            sustainabilityScore = Math.max(0, 30 - deficitPercent);
        }
    }

    // Runtime estimation
    // If sustainable: indefinite
    // If not: how long until battery depletes
    let estimatedRuntimeHours;
    if (netEnergyBalance >= 0) {
        estimatedRuntimeHours = Infinity;
    } else {
        // Daily deficit drains battery
        const dailyDeficit = Math.abs(netEnergyBalance);
        const daysUntilDepletion = batteryUsableWh / dailyDeficit;
        estimatedRuntimeHours = daysUntilDepletion * 24;
    }

    // Solar-to-load ratio
    const solarToLoadRatio = loadDailyWh > 0 ? solarDailyWh / loadDailyWh : Infinity;

    // Battery cycles per day (rough estimate)
    const batteryCyclesPerDay = loadDailyWh / batteryUsableWh;

    return {
        // Energy metrics
        solarDailyWh,
        loadDailyWh,
        netEnergyBalance,

        // Battery metrics
        batteryAutonomyHours,
        autonomyDays,
        batteryCyclesPerDay,

        // System status
        sustainabilityStatus,
        sustainabilityScore: Math.round(sustainabilityScore),

        // Runtime
        estimatedRuntimeHours,
        estimatedRuntimeDays: estimatedRuntimeHours / 24,

        // Ratios
        solarToLoadRatio,
        peakDemandW
    };
}

/**
 * Simulates battery state of charge over 24 hours.
 * 
 * @param {number[]} solarProfile - Hourly solar generation (Wh)
 * @param {number[]} loadProfile - Hourly load consumption (Wh)
 * @param {Object} batteryStorage - Battery storage configuration
 * @param {number} initialSoC - Initial state of charge (0-1)
 * @returns {number[]} Array of 24 hourly SoC values (0-1)
 */
export function simulateBatterySoC(solarProfile, loadProfile, batteryStorage, initialSoC = 0.5) {
    const { totalEnergyWh, usableEnergyWh, roundTripEfficiency } = batteryStorage;
    const maxSoC = 1;
    const minSoC = 1 - (usableEnergyWh / totalEnergyWh);

    const socProfile = [initialSoC];
    let currentSoC = initialSoC;

    for (let hour = 0; hour < 24; hour++) {
        const solarWh = solarProfile[hour] * roundTripEfficiency;
        const loadWh = loadProfile[hour];

        // Net energy flow (positive = charging, negative = discharging)
        const netFlowWh = solarWh - loadWh;

        // Convert to SoC change
        const socChange = netFlowWh / totalEnergyWh;

        // Apply constraints
        currentSoC = Math.max(minSoC, Math.min(maxSoC, currentSoC + socChange));

        socProfile.push(currentSoC);
    }

    return socProfile;
}

/**
 * Simulates energy surplus/deficit over 24 hours.
 * 
 * @param {number[]} solarProfile - Hourly solar generation (Wh)
 * @param {number[]} loadProfile - Hourly load consumption (Wh)
 * @returns {number[]} Array of 24 hourly surplus/deficit values (Wh)
 */
export function simulateSurplusDeficit(solarProfile, loadProfile) {
    return solarProfile.map((solar, i) => solar - loadProfile[i]);
}


// ============================================
// REAL-TIME / TIME-OF-DAY CALCULATIONS
// ============================================

/**
 * Calculates solar power output for a specific hour of the day.
 * Solar is only generated during daylight hours (6:00 - 18:00).
 * 
 * @param {Object} solarOutput - Solar configuration output
 * @param {number} currentHour - Current hour (0-23)
 * @param {number} sunHours - Peak sun hours configuration
 * @returns {number} Current solar power in Watts
 */
export function getSolarPowerAtHour(solarOutput, currentHour, sunHours) {
    const { effectiveCapacityW } = solarOutput;

    // Define sunrise and sunset (strictly as requested)
    const sunrise = 8;
    const sunset = 18;
    const solarNoon = 12;

    // No solar power outside daylight hours
    if (currentHour < sunrise || currentHour >= sunset) {
        return 0;
    }

    // Gaussian distribution for solar intensity
    const sigma = sunHours / 2.5;
    const intensity = Math.exp(-Math.pow(currentHour - solarNoon, 2) / (2 * sigma * sigma));

    // Scale to peak capacity (at noon = ~100% of effective capacity)
    return effectiveCapacityW * intensity;
}

/**
 * Calculates load power consumption for a specific hour.
 * Considers which loads are active at the given hour.
 * 
 * @param {Array} loads - Array of load configurations
 * @param {number} currentHour - Current hour (0-23)
 * @returns {number} Current load power in Watts
 */
export function getLoadPowerAtHour(loads, currentHour) {
    let totalPower = 0;

    loads.forEach(load => {
        const loadType = LOAD_TYPES[load.type] || LOAD_TYPES.mixed;
        const effectivePowerW = load.powerW / loadType.powerFactor;
        const startHour = load.startHour || 0;
        const hoursOn = load.hoursPerDay;

        // Check if load is active at current hour
        // Handle wrap-around (e.g., start at 22:00, run for 6 hours)
        let isActive = false;
        for (let i = 0; i < hoursOn; i++) {
            const activeHour = (startHour + i) % 24;
            if (activeHour === currentHour) {
                isActive = true;
                break;
            }
        }

        if (isActive) {
            totalPower += effectivePowerW;
        }
    });

    return totalPower;
}

/**
 * Calculates real-time energy flow between components.
 * 
 * @param {number} solarPowerW - Current solar power generation (W)
 * @param {number} loadPowerW - Current load consumption (W)
 * @returns {Object} Flow information
 */
export function calculateEnergyFlow(solarPowerW, loadPowerW) {
    const netFlow = solarPowerW - loadPowerW;

    return {
        solarPowerW,
        loadPowerW,
        netFlowW: netFlow,
        isCharging: netFlow > 0,
        isDischarging: netFlow < 0,
        batteryFlowW: Math.abs(netFlow),
        solarToBatteryW: netFlow > 0 ? netFlow : 0,
        solarToLoadW: Math.min(solarPowerW, loadPowerW),
        batteryToLoadW: netFlow < 0 ? Math.abs(netFlow) : 0
    };
}

/**
 * Enhanced battery SoC simulation with power failure detection.
 * Returns detailed simulation including any power failure events.
 * 
 * @param {number[]} solarProfile - Hourly solar generation (Wh)
 * @param {number[]} loadProfile - Hourly load consumption (Wh)
 * @param {Object} batteryStorage - Battery storage configuration
 * @param {number} initialSoC - Initial state of charge (0-1)
 * @returns {Object} Detailed simulation results
 */
export function simulateBatterySoCDetailed(solarProfile, loadProfile, batteryStorage, initialSoC = 0.8) {
    const { totalEnergyWh, roundTripEfficiency, usableEnergyWh } = batteryStorage;
    const maxSoC = 1;
    const minSoC = 1 - (usableEnergyWh / totalEnergyWh); // DoD limit

    const socProfile = [initialSoC];
    const flowProfile = [];
    const powerFailures = [];
    let currentSoC = initialSoC;
    let hasPowerFailure = false;

    for (let hour = 0; hour < 24; hour++) {
        const solarWh = solarProfile[hour] * Math.sqrt(roundTripEfficiency); // Charging efficiency
        const loadWh = loadProfile[hour];

        // Net energy flow
        const netFlowWh = solarWh - loadWh;

        // Calculate SoC change
        let socChange = netFlowWh / totalEnergyWh;

        // Apply discharge efficiency when discharging
        if (netFlowWh < 0) {
            socChange = netFlowWh / (totalEnergyWh * Math.sqrt(roundTripEfficiency));
        }

        // Calculate new SoC
        let newSoC = currentSoC + socChange;

        // Check for power failure (battery hits DoD limit while load demands power)
        if (newSoC <= minSoC && loadWh > solarWh) {
            hasPowerFailure = true;
            powerFailures.push({
                hour,
                solarWh,
                loadWh,
                deficit: loadWh - solarWh,
                socAtFailure: currentSoC
            });
            newSoC = minSoC; // Battery bottoms out at DoD limit
        }

        // Apply constraints
        currentSoC = Math.max(minSoC, Math.min(maxSoC, newSoC));

        socProfile.push(currentSoC);
        flowProfile.push({
            hour,
            solarWh,
            loadWh,
            netFlowWh,
            socBefore: socProfile[hour],
            socAfter: currentSoC,
            isCharging: netFlowWh > 0
        });
    }

    return {
        socProfile,
        flowProfile,
        powerFailures,
        hasPowerFailure,
        minSoCReached: Math.min(...socProfile),
        maxSoCReached: Math.max(...socProfile),
        finalSoC: currentSoC,
        minSoCLimit: minSoC
    };
}

/**
 * Calculates battery autonomy at a specific hour based on current load.
 * 
 * @param {number} currentSoC - Current state of charge (0-1)
 * @param {number} minSoC - Minimum SoC (DoD limit)
 * @param {number} totalEnergyWh - Total battery capacity
 * @param {number} currentLoadW - Current load power draw
 * @returns {number} Remaining autonomy in hours
 */
export function calculateRemainingAutonomy(currentSoC, minSoC, totalEnergyWh, currentLoadW) {
    if (currentLoadW <= 0) return Infinity;

    const usableEnergyRemaining = (currentSoC - minSoC) * totalEnergyWh;
    if (usableEnergyRemaining <= 0) return 0;

    return usableEnergyRemaining / currentLoadW;
}

/**
 * Determines if the system is sustainable over a 24-hour cycle.
 * A system is unsustainable if battery SoC hits DoD limit during the cycle.
 * 
 * @param {Object} simResult - Result from simulateBatterySoCDetailed
 * @param {Object} systemAnalysis - System analysis results
 * @returns {Object} Enhanced sustainability status
 */
export function getEnhancedSustainabilityStatus(simResult, systemAnalysis) {
    const { hasPowerFailure, powerFailures, minSoCReached, minSoCLimit } = simResult;
    const margin = minSoCReached - minSoCLimit;

    if (hasPowerFailure) {
        return {
            status: 'unsustainable',
            message: 'POWER FAILURE DETECTED',
            detail: `Battery depleted at hour ${powerFailures[0]?.hour}:00`,
            score: 0,
            failureHour: powerFailures[0]?.hour
        };
    }

    if (margin < 0.05) {
        return {
            status: 'critical',
            message: 'CRITICAL - NEAR FAILURE',
            detail: `Battery margin only ${(margin * 100).toFixed(1)}%`,
            score: Math.max(0, Math.round(margin * 500)),
            failureHour: null
        };
    }

    if (systemAnalysis.netEnergyBalance < 0) {
        return {
            status: 'unstable',
            message: 'UNSTABLE - DAILY DEFICIT',
            detail: 'System cannot sustain indefinitely',
            score: Math.round(30 + margin * 100),
            failureHour: null
        };
    }

    if (systemAnalysis.netEnergyBalance >= 0 && margin > 0.2) {
        return {
            status: 'sustainable',
            message: 'SUSTAINABLE',
            detail: 'System is self-sufficient',
            score: Math.min(100, Math.round(70 + (systemAnalysis.solarToLoadRatio - 1) * 30)),
            failureHour: null
        };
    }

    return {
        status: 'marginal',
        message: 'MARGINAL',
        detail: 'System is borderline sustainable',
        score: Math.round(50 + margin * 100),
        failureHour: null
    };
}


// ============================================
// UTILITY FUNCTIONS
// ============================================

/**
 * Formats energy value with appropriate unit.
 * @param {number} wh - Energy in Wh
 * @returns {string} Formatted string
 */
export function formatEnergy(wh) {
    if (wh >= 1000000) {
        return `${(wh / 1000000).toFixed(2)} MWh`;
    } else if (wh >= 1000) {
        return `${(wh / 1000).toFixed(2)} kWh`;
    }
    return `${wh.toFixed(1)} Wh`;
}

/**
 * Formats power value with appropriate unit.
 * @param {number} w - Power in W
 * @returns {string} Formatted string
 */
export function formatPower(w) {
    if (w >= 1000000) {
        return `${(w / 1000000).toFixed(2)} MW`;
    } else if (w >= 1000) {
        return `${(w / 1000).toFixed(2)} kW`;
    }
    return `${w.toFixed(1)} W`;
}

/**
 * Formats time duration.
 * @param {number} hours - Duration in hours
 * @returns {string} Formatted string
 */
export function formatDuration(hours) {
    if (!isFinite(hours)) return '∞ (Indefinite)';
    if (hours >= 24) {
        const days = hours / 24;
        return `${days.toFixed(1)} days`;
    }
    return `${hours.toFixed(1)} hours`;
}

/**
 * Formats percentage.
 * @param {number} value - Value as decimal (0-1)
 * @returns {string} Formatted string
 */
export function formatPercent(value) {
    return `${(value * 100).toFixed(1)}%`;
}
